version: '3.4'

services:
  ordersmi:
    image: ${DOCKER_REGISTRY-}ordersmi
    build:
      context: .
      dockerfile: OrderSmi/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"